title: Karin Isaev
logo: "/images/DSC06706 2.jpeg"
description: >
  Computational Biologist at <a href="https://www.pioneer-labs.org/#mission" target="_blank">Pioneer Labs</a><br><br>
  <a href="/Experience">Experience</a> &nbsp;&middot;&nbsp;
  <a href="/Projects">Projects</a> &nbsp;&middot;&nbsp;
  <a href="https://scholar.google.ca/citations?hl=en&user=q5Hzub8AAAAJ&view_op=list_works" target="_blank">Publications</a><br>
  <a href="https://geekygenomics.substack.com/" target="_blank">Blog</a> &nbsp;&middot;&nbsp;
  <a href="https://www.kisaev.com/" target="_blank">Photography</a><br><br>
  karin[.]isaev[@]gmail[.]com
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
